
SUPPORTED_TEAM_NAMES = [
    'Minnesota Timberwolves',
    'Memphis Grizzlies',
    'Golden State Warriors',
    'Boston Celtics',
    'Milwaukee Bucks',
    'Dallas Mavericks',
    'Phoenix Suns',
    'Philadelphia 76ers',
    'Miami Heat',
    'Toronto Raptors',
    'New Orleans Pelicans',
    'Utah Jazz',
    'Denver Nuggets',
    'Chicago Bulls',
    'Atlanta Hawks',
    'Brooklyn Nets',
    'Cleveland Cavaliers',
    'LA Clippers',
    'San Antonio Spurs',
    'Charlotte Hornets',
    'Sacramento Kings',
    'Portland Trail Blazers',
    'Los Angeles Lakers',
    'Indiana Pacers',
    'Washington Wizards',
    'Orlando Magic',
    'Oklahoma City Thunder',
    'Houston Rockets',
    'New York Knicks',
    'Detroit Pistons',
]
