from dataclasses import dataclass
from datetime import datetime
from enum import Enum
from typing import Optional


@dataclass
class LGFDataNames:
    SEASON_ID = 'SEASON_ID'
    TEAM_ID = 'TEAM_ID'
    TEAM_ABBREVIATION = "TEAM_ABBREVIATION"
    TEAM_NAME = "TEAM_NAME"
    GAME_ID = "GAME_ID"
    GAME_DATE = "GAME_DATE"
    MATCHUP = "MATCHUP"
    MINUTES = "MIN"
    POINTS = "PTS"
    WIN_LOSS = "WL"


@dataclass
class BoxscoreV2Names:
    GAME_ID = "GAME_ID"
    TEAM_ID = "TEAM_ID"
    TEAM_ABBREVIATION = "TEAM_ABBREVIATION"
    PLAYER_ID = "PLAYER_ID"
    PLAYER_NAME = "PLAYER_NAME"
    START_POSITION = "START_POSITION"
    MIN = "MIN"
    FGM = "FGM"
    FGA = "FGA"
    FG3M = "FG3M"
    FG3A = "FG3A"
    FTM = "FTM"
    FTA = "FTA"
    OREB = "OREB"
    DREB = "DREB"
    AST = "AST"
    STL = "STL"
    BLK = "BLK"
    TO = "TO"
    PF = "PF"
    PTS = "PTS"
    PLUS_MINUS = "PLUS_MINUS"


@dataclass
class PlayByPlay2Names:
    GAME_ID = "GAME_ID"
    HOMEDESCRIPTION = "HOMEDESCRIPTION"
    VISITORDESCRIPTION = "VISITORDESCRIPTION"
    NEUTRALDESCRIPTION = "NEUTRALDESCRIPTION"
    SECONDS_PLAYED = "SECONDS_PLAYED"
    SCORE = "SCORE"
    PLAYER1_ID = "PLAYER1_ID"
    PLAYER1_NAME = "PLAYER1_NAME"
    PLAYER1_TEAM_ID = "PLAYER1_TEAM_ID"
    PLAYER2_ID = "PLAYER2_ID"
    PLAYER2_NAME = "PLAYER2_NAME"
    PLAYER2_TEAM_ID = "PLAYER2_TEAM_ID"
    PLAYER3_ID = "PLAYER3_ID"
    PLAYER3_NAME = "PLAYER3_NAME"
    PLAYER3_TEAM_ID = "PLAYER3_TEAM_ID"
    POSSESSION_ID = "POSSESSION_ID"
    POSSESSION_ATTEMPT_ID = "POSSESSION_ATTEMPT_ID"
    EVENTNUM = "EVENTNUM"


@dataclass
class ShotPlaysNames:
    GAME_ID = "GAME_ID"
    SECONDS_PLAYED = "SECONDS_PLAYED"
    SCORE = "SCORE"
    SCORE_OPPONENT = "SCORE_OPPONENT"
    TEAM_ID = "TEAM_ID"
    PLAYER_ID = "PLAYER_ID"
    LINEUP = "LINEUP"
    LINEUP_OPPONENT = "LINEUP_OPPONENT"
    SHOT_DISTANCE = "DISTANCE"
    SUCCESS = "SUCCESS"
    SHOT_TYPE = "SHOT_TYPE"
    INPLAY_ID = "INPLAY_ID"


@dataclass
class RotationNames:
    GAME_ID = "GAME_ID"
    TEAM_ID = "TEAM_ID"
    PERSON_ID = "PERSON_ID"
    IN_TIME_REAL = "IN_TIME_REAL"
    OUT_TIME_REAL = "OUT_TIME_REAL"
    PLAYERS_PTS = "PLAYERS_PTS"
    PD_DIFF = "PT_DIFF"
    IN_TIME_SECONDS_PLAYED = "IN_TIME_SECONDS_PLAYED"
    OUT_TIME_SECONDS_PLAYED = "OUT_TIME_SECONDS_PLAYED"


@dataclass
class TeamPossessionNames:
    GAME_ID = "GAME_ID"
    SECONDS_PLAYED = "SECONDS_PLAYED"
    DURATION = "DURATION"
    TEAM_ID = "TEAM_ID"
    IN_POSSESSION = "IN_POSSESSION"
    PRIOR_PLAY_ENDING = "PRIOR_PLAY_ENDING"
    LINEUP = "LINEUP"
    LINEUP_OPPONENT = "LINEUP_OPPONENT"
    POINTS = "POINTS"
    POINTS_OPPONENT = "POINTS_OPPONENT"
    THREE_POINTERS_SHOT = "THREE_POINTERS_SHOT"
    TWO_POINTERS_SHOT = "TWO_POINTERS_SHOT"
    THREE_POINTERS_SHOT_OPPONENT = "THREE_POINTERS_SHOT_OPPONENT"
    TWO_POINTERS_SHOT_OPPONENT = "TWO_POINTERS_SHOT_OPPONENT"
    FOULS = "FOULS"
    FOULS_OPPONENT = "FOULS_OPPONENT"
    REBOUNDS = "REBOUNDS"
    REBOUNDS_OPPONENT = "REBOUNDS_OPPONENT"


@dataclass
class TeamInPlayLineupNames:
    GAME_ID = "GAME_ID"
    TEAM_ID = "TEAM_ID"
    PERIOD = "PERIOD"
    SECONDS_PLAYED_START = "SECONDS_PLAYED_START"
    SECONDS_PLAYED_END = "SECONDS_PLAYED_END"
    LINEUP = "LINEUP"
    LINEUP_OPPONENT = "LINEUP_OPPONENT"
    INPLAY_ID = "INPLAY_ID"


@dataclass
class LineupPlayByPlaysNames:
    GAME_ID = "GAME_ID"
    TEAM_ID_OFFENSE = "TEAM_ID_OFFENSE"
    TEAM_ID_DEFENSE = "TEAM_ID_DEFENSE"
    POSSESSION_ID = "POSSESSION_ID"
    POSSESSION_ATTEMPT_ID = "POSSESSION_ATTEMPT_ID"
    SCORE_OFFENSE = "SCORE_OFFENSE"
    SCORE_DEFENSE = "SCORE_DEFENSE"
    SECONDS_PLAYED_START = "SECONDS_PLAYED_START"
    SECONDS_PLAYED_END = "SECONDS_PLAYED_END"
    FIELD_GOAL_ATTEMPTS = "FIELD_GOAL_ATTEMPTS"
    POINTS = "POINTS"
    FREE_THROW_ATTEMPTS = "FREE_THROW_ATTEMPTS"
    LINEUP_OFFENSE = "LINEUP_OFFENSE"
    LINEUP_DEFENSE = "LINEUP_DEFENSE"
    INPLAY_ID = "INPLAY_ID"
    PLAY_END_REASON = "PLAY_END_REASON"
    TEAM_PREV_POSSESION = "TEAM_PREV_POSSESSION"
    PRECEEDED_BY = "PRECEEDED_BY"



@dataclass
class PosessionNames:
    GAME_ID = "GAME_ID"
    TEAM_ID_OFFENSE = "TEAM_ID_OFFENSE"
    TEAM_ID_DEFENSE = "TEAM_ID_DEFENSE"
    POSSESSION_ID = "POSSESSION_ID"
    SECONDS_PLAYED_START = "SECONDS_PLAYED_START"
    SECONDS_PLAYED_END = "SECONDS_PLAYED_END"
    LINEUP_OFFENSE = "LINEUP_OFFENSE"
    LINEUP_DEFENSE = "LINEUP_DEFENSE"
    POINTS = "POINTS"
    FIELD_GOAL_ATTEMPTS = "FIELD_GOAL_ATTEMPTS"
    FREE_THROW_ATTEMPTS = "FREE_THROW_ATTEMPTS"
    SCORE_OFFENSE = "SCORE_OFFENSE"
    SCORE_DEFENSE = "SCORE_DEFENSE"


@dataclass
class PlayerOffensePlayByPlaysNames:
    GAME_ID = "GAME_ID"
    TEAM_ID = "TEAM_ID"
    POSSESSION_ID = "POSSESSION_ID"
    PLAYER_ID = "PLAYER_ID"
    POINTS = "PLAYER_POINTS"
    ASSISTS = "PLAYER_ASSISTS"
    REBOUNDS = "PLAYER_REBOUNDS"
    TURNOVERS = "PLAYER_TURNOVERS"
    FOULS = "PLAYER_FOULS"
    THREE_POINTERS_ATTEMPTED = "PLAYER_THREE_POINTERS_ATTEMPTED"
    THREE_POINTERS_MADE = "PLAYER_THREE_POINTERS_MADE"
    TWO_POINTERS_ATTEMPTED = "PLAYER_TWO_POINTERS_ATTEMPTED"
    TWO_POINTERS_MADE = "PLAYER_TWO_POINTERS_MADE"
    FREE_THROWS_ATTEMPTED = "PLAYER_FREE_THROWS_ATTEMPTED"
    FREE_THROWS_MADE = "PLAYER_FREE_THROWS_MADE"


@dataclass
class PlayerDefensePlayByPlaysNames:
    GAME_ID = "GAME_ID"
    TEAM_ID = "TEAM_ID"
    POSSESSION_ID = "POSSESSION_ID"
    PLAYER_ID = "PLAYER_ID"
    REBOUNDS = "PLAYER_REBOUNDS"
    BLOCKS = "PLAYER_BLOCKS"
    STEALS = "PLAYER_STEALS"
    FOULS = "PLAYER_FOULS"


@dataclass
class GamePlayerNames:
    PLAYER_ID = "PLAYER_ID"
    GAME_ID = "GAME_ID"
    TEAM_ID = "TEAM_ID"
    PLAYER_NAME = "NAME"
    MINUTES = "MINUTES"
    POINTS = "POINTS"
    THREE_POINTERS_MADE = "THREE_POINTERS_MADE"
    THREE_POINTERS_ATTEMPTED = "THREE_POINTERS_ATTEMPTED"
    TWO_POINTERS_MADE = "TWO_POINTERS_MADE"
    TWO_POINTERS_ATTEMPTED = "TWO_POINTERS_ATTEMPTED"
    FREE_THROWS_MADE = "FREE_THROWS_MADE"
    FREE_THROWS_ATTEMPTED = "FREE_THROWS_ATTEMPTED"
    PLUS_MINUS = "PLUS_MINUS"
    BLOCKS = "BLOCKS"
    STEALS = "STEALS"
    ASSISTS = "ASSISTS"
    OFFENSIVE_REBOUNDS = "OFFENSIVE_REBOUNDS"
    DEFENSIVE_REBOUNDS = "DEFENSIVE_REBOUNDS"
    TURNOVERS = "TURNOVERS"
    FOULS = "FOULS"


@dataclass
class GameTeamNames:
    GAME_ID = "GAME_ID"
    TEAM_ID = "TEAM_ID"
    TEAM_NAME = "TEAM_NAME"
    TEAM_NAME_ABBR = "TEAM_NAME_ABBR"
    TEAM_ID_OPPONENT = "TEAM_ID_OPPONENT"
    LOCATION = "LOCATION"
    SCORE = "SCORE"
    SCORE_OPPONENT = "SCORE_OPPONENT"
    WON = "WON"


@dataclass
class GameNames:
    GAME_ID = "GAME_ID"
    START_DATE = "START_DATE"
    MINUTES = "MINUTES"
    SEASON_ID = "SEASON_ID"
