from dataclasses import dataclass
from datetime import datetime
from enum import Enum
from typing import Optional


@dataclass
class LGFDataNames:
    SEASON_ID = 'SEASON_ID'
    TEAM_ID = 'TEAM_ID'
    TEAM_ABBREVIATION = "TEAM_ABBREVIATION"
    TEAM_NAME = "TEAM_NAME"
    GAME_ID = "GAME_ID"
    GAME_DATE = "GAME_DATE"
    MATCHUP = "MATCHUP"
    MINUTES = "MIN"
    POINTS = "PTS"
    WIN_LOSS = "WL"


@dataclass
class BoxscoreV2Names:
    GAME_ID = "GAME_ID"
    TEAM_ID = "TEAM_ID"
    TEAM_ABBREVIATION = "TEAM_ABBREVIATION"
    PLAYER_ID = "PLAYER_ID"
    PLAYER_NAME = "PLAYER_NAME"
    START_POSITION = "START_POSITION"
    MIN = "MIN"
    FGM = "FGM"
    FGA = "FGA"
    FG3M = "FG3M"
    FG3A = "FG3A"
    FTM = "FTM"
    FTA = "FTA"
    OREB = "OREB"
    DREV = "DREB"
    AST = "AST"
    STL = "STL"
    BLK = "BLK"
    TO = "TO"
    PF = "PF"
    PTS = "PTS"
    PLUS_MINUS = "PLUS_MINUS"


@dataclass
class PlayByPlay2Names:
    GAME_ID = "GAME_ID"
    HOMEDESCRIPTION = "HOMEDESCRIPTION"
    VISITORDESCRIPTION = "VISITORDESCRIPTION"
    NEUTRALDESCRIPTION = "NEUTRALDESCRIPTION"
    SECONDS_PLAYED = "SECONDS_PLAYED"
    SCORE = "SCORE"
    PLAYER1_ID = "PLAYER1_ID"
    PLAYER1_NAME = "PLAYER1_NAME"
    PLAYER1_TEAM_ID = "PLAYER1_TEAM_ID"
    PLAYER2_ID = "PLAYER1_ID"
    PLAYER2_NAME = "PLAYER1_NAME"
    PLAYER2_TEAM_ID = "PLAYER1_TEAM_ID"
    PLAYER3_ID = "PLAYER1_ID"
    PLAYER3_NAME = "PLAYER1_NAME"
    PLAYER3_TEAM_ID = "PLAYER1_TEAM_ID"


@dataclass
class ShotPlaysNames:
    SECONDS_PLAYED = "SECONDS_PLAYED"
    SCORE = "SCORE"
    SCORE_OPPONENT = "SCORE_OPPONENT"
    TEAM_ID = "TEAM_ID"
    PLAYER_ID = "PLAYER_ID"
    LINEUP = "LINEUP"
    LINEUP_OPPONENT = "LINEUP_OPPONENT"
    SHOT_DISTANCE = "DISTANCE"
    SUCCESS = "SUCCESS"
    SHOT_TYPE = "SHOT_TYPE"
    PRECEEDING_PLAY = "PRECEEDING_PLAY"
    SUCCEEDING_PLAY = "SUCCEEDING_PLAY"


@dataclass
class RotationNames:
    GAME_ID = "GAME_ID"
    TEAM_ID = "TEAM_ID"
    PERSON_ID = "PERSON_ID"
    IN_TIME_REAL = "IN_TIME_REAL"
    OUT_TIME_REAL = "OUT_TIME_REAL"
    PLAYERS_PTS = "PLAYERS_PTS"
    PD_DIFF = "PT_DIFF"
    IN_TIME_SECONDS_PLAYED = "IN_TIME_SECONDS_PLAYED"
    OUT_TIME_SECONDS_PLAYED = "OUT_TIME_SECONDS_PLAYED"


@dataclass
class TeamPossessionNames:
    SECONDS_PLAYED = "SECONDS_PLAYED"
    DURATION = "DURATION"
    TEAM_ID = "TEAM_ID"
    IN_POSSESSION = "IN_POSSESSION"
    PRIOR_PLAY_ENDING = "PRIOR_PLAY_ENDING"
    LINEUP = "LINEUP"
    LINEUP_OPPONENT = "LINEUP_OPPONENT"
    POINTS = "POINTS"
    POINTS_OPPONENT = "POINTS_OPPONENT"
    THREE_POINTERS_SHOT = "THREE_POINTERS_SHOT"
    TWO_POINTERS_SHOT = "TWO_POINTERS_SHOT"
    THREE_POINTERS_SHOT_OPPONENT = "THREE_POINTERS_SHOT_OPPONENT"
    TWO_POINTERS_SHOT_OPPONENT = "TWO_POINTERS_SHOT_OPPONENT"
    FOULS = "FOULS"
    FOULS_OPPONENT = "FOULS_OPPONENT"
    REBOUNDS = "REBOUNDS"
    REBOUNDS_OPPONENT = "REBOUNDS_OPPONENT"


@dataclass
class TeamInPlayLineupNames:
    TEAM_ID = "TEAM_ID"
    PERIOD = "PERIOD"
    SECONDS_PLAYED_START = "SECONDS_PLAYED_START"
    SECONDS_PLAYED_END = "SECONDS_PLAYED_END"
    LINEUP = "LINEUP"
    LINEUP_OPPONENT = "LINEUP_OPPONENT"


@dataclass
class PlayerShotData:
    TEAM_ID = "TEAM_ID"
    PLAYER_ID = "PLAYER_ID"
